alias logs='journalctl -f'
alias end-logs='journalctl -xe'
alias start='systemctl start'
alias stop='systemctl stop'
alias status='systemctl status'
alias restart='systemctl restart'
alias update-bashrc='source ~/.bashrc'
alias campfire='aafire -driver curses'
alias check-moon='curl wttr.in/Moon'
alias check-weather='curl wttr.in'
alias crypto-rates='curl rate.sx'
alias docker-clear='sudo docker stop $(docker ps -a -q)  && docker rm $(docker ps -a -q) && docker rmi -f $(docker images -a -q)'
alias docker-rm='docker rmi -f $(docker images -a -q)'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias install='sudo apt-get install'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias pull='cd /home/tmeralus/github/ansible'
alias samba-deps='cd /run/user/1000/gvfs/smb-share:server=brain,share=departments'
alias search='apt-cache search'
alias snano='sudo nano'
alias start-matrix='cmatrix'
alias tartar='tar -zxvf'
alias update='sudo apt-get update'
alias update-bashrc='source ~/.bashrc'
alias upgrade='sudo apt-get upgrade -y'
